### ISSUE TITLE
refactor: spelling mistakes check for every page

### ISSUE THREAD

**Issue by marcpinet** [2019-2020-ps6/2022-2023-ps6-4-grands-corsaires#211]

**Comment by rodriguezarthur** [comment]
![img-1](https://github.com/2019-2020-ps6/2022-2023-ps6-4-grands-corsaires/assets/110430299/a2c41fb3-061b-4e53-abc4-1c6b9326600a)
![img-2](https://github.com/2019-2020-ps6/2022-2023-ps6-4-grands-corsaires/assets/110430299/f8e1ca1e-48ca-45a4-b48e-3f255229ed29)
![img-3](https://github.com/2019-2020-ps6/2022-2023-ps6-4-grands-corsaires/assets/110430299/32874800-010a-43a8-a925-edc497e85d24)
![img-4](https://github.com/2019-2020-ps6/2022-2023-ps6-4-grands-corsaires/assets/110430299/501633e5-d21f-4686-a759-3305848f3fba)
